package com.chaima.truekeo.utils

object BrandData {

    val knownBrands: List<String> = listOf(
        // Tecnología / Electrónica general
        "Apple",
        "Samsung",
        "Xiaomi",
        "Huawei",
        "Sony",
        "LG",
        "Google",
        "Microsoft",
        "Nokia",
        "Motorola",
        "OnePlus",
        "Realme",
        "Oppo",
        "Vivo",
        "Honor",
        "Nothing",
        "HTC",
        "ZTE",
        "Alcatel",
        "BlackBerry",
        "Fairphone",
        "Asus ROG",
        "Redmi",
        "Poco",
        "Infinix",
        "Tecno",
        "Meizu",

        // Informática / Ordenadores / Componentes
        "HP",
        "Lenovo",
        "Asus",
        "Acer",
        "Dell",
        "MSI",
        "Razer",
        "Gigabyte",
        "Intel",
        "AMD",
        "NVIDIA",
        "Corsair",
        "Logitech",
        "SteelSeries",
        "HyperX",
        "Kingston",
        "Western Digital",
        "Seagate",
        "Sandisk",
        "Crucial",
        "ASRock",
        "NZXT",
        "Thermaltake",
        "Be Quiet!",
        "Cooler Master",
        "Alienware",
        "Framework",

        // Gaming / Consolas
        "PlayStation",
        "Xbox",
        "Nintendo",
        "Valve",
        "Steam Deck",

        // Consolas / Retro
        "Atari",
        "SEGA",
        "SNK",
        "Neo Geo",
        "Commodore",
        "Amiga",
        "Intellivision",
        "ColecoVision",

        // Gaming PC / Ecosistema
        "Alienware",
        "Asus ROG",
        "MSI Gaming",
        "Predator",
        "NZXT",
        "CyberPowerPC",
        "iBuyPower",
        "Origin PC",

        // Periféricos gaming
        "Razer",
        "Logitech G",
        "SteelSeries",
        "Corsair",
        "HyperX",
        "Roccat",
        "Cooler Master",
        "Trust Gaming",
        "Redragon",
        "Glorious",
        "Keychron",
        "Akko",
        "Ducky",
        "Xtrfy",

        // Fotografía / Vídeo
        "Canon",
        "Nikon",
        "Sony Alpha",
        "Fujifilm",
        "Panasonic",
        "Olympus",
        "Leica",
        "GoPro",
        "DJI",
        "Insta360",
        "Sigma",
        "Tamron",
        "Hasselblad",

        // Audio
        "Bose",
        "JBL",
        "Beats",
        "Sennheiser",
        "Marshall",
        "AKG",
        "Bang & Olufsen",
        "Sonos",
        "Skullcandy",
        "Audio-Technica",
        "Shure",
        "Beyerdynamic",
        "Edifier",
        "Anker Soundcore",

        // Wearables
        "Garmin",
        "Fitbit",
        "Amazfit",
        "Withings",
        "Polar",
        "Suunto",
        "Whoop",

        // Electrodomésticos / Hogar
        "Bosch",
        "Siemens",
        "Philips",
        "Whirlpool",
        "Balay",
        "Tefal",
        "Rowenta",
        "Braun",
        "Miele",
        "Electrolux",
        "Candy",
        "Beko",
        "AEG",
        "Indesit",
        "Cecotec",
        "Orbegozo",
        "Ufesa",
        "Krups",
        "Delonghi",

        // Automoción / Accesorios
        "BMW",
        "Mercedes-Benz",
        "Audi",
        "Volkswagen",
        "Toyota",
        "Renault",
        "Peugeot",
        "Seat",
        "Ford",
        "Tesla",
        "Hyundai",
        "Kia",
        "Mazda",
        "Volvo",
        "Skoda",
        "Dacia",
        "Opel",
        "Honda",
        "Yamaha",
        "Kawasaki",

        // Moda / Ropa general
        "Nike",
        "Adidas",
        "Puma",
        "Reebok",
        "New Balance",
        "Under Armour",
        "Zara",
        "H&M",
        "Pull&Bear",
        "Bershka",
        "Uniqlo",
        "Levi's",
        "Tommy Hilfiger",
        "Calvin Klein",
        "Lacoste",
        "Ralph Lauren",
        "Jordan",
        "Stradivarius",
        "Mango",
        "Massimo Dutti",
        "Springfield",
        "C&A",
        "Primark",
        "Lefties",
        "Kiabi",
        "Desigual",
        "Cortefiel",
        "Oysho",
        "Women’secret",
        "Jack & Jones",
        "Only",
        "Vero Moda",
        "Pepe Jeans",
        "Benetton",
        "Guess",
        "Dockers",
        "Diesel",
        "Superdry",
        "Gant",
        "Scalpers",
        "Hackett",
        "Carhartt",
        "Patagonia",
        "The North Face",
        "Columbia",
        "Helly Hansen",
        "Champion",
        "Fila",
        "Kappa",
        "Umbro",
        "Quiksilver",
        "Billabong",
        "Rip Curl",

        // Calzado
        "Converse",
        "Vans",
        "Dr. Martens",
        "Timberland",
        "Skechers",
        "Birkenstock",
        "Havaianas",
        "Salomon",
        "Merrell",
        "Asics",
        "Mizuno",
        "Hoka",
        "Brooks",
        "Saucony",

        // Lujo / Premium
        "Gucci",
        "Prada",
        "Louis Vuitton",
        "Chanel",
        "Dior",
        "Versace",
        "Fendi",
        "Givenchy",
        "Balenciaga",
        "Saint Laurent",
        "Loewe",
        "Hermès",
        "Bottega Veneta",
        "Moncler",
        "Canada Goose",

        // Belleza / Cuidado personal
        "L'Oréal",
        "Maybelline",
        "Nivea",
        "Dove",
        "Garnier",
        "Clinique",
        "MAC",
        "Sephora",
        "The Ordinary",
        "Kiehl's",
        "Neutrogena",
        "La Roche-Posay",
        "Vichy",
        "CeraVe",
        "Avène",

        // Otros / General
        "Ikea",
        "Decathlon",
        "Lego",
        "Hasbro",
        "Mattel",
        "Funko",
        "Dyson",
        "Xiaomi Home",
        "Muji",
        "Flying Tiger",
        "Miniso",
        "AliExpress",
        "Amazon Basics",
        "Shein",

        // Genéricos útiles para UX
        "Sin marca",
        "Otra",
        "Marca local",
        "Artesanal"
    )

    fun search(query: String, limit: Int = 8): List<String> {
        if (query.isBlank()) return emptyList()

        return knownBrands
            .filter { it.contains(query, ignoreCase = true) }
            .take(limit)
    }

    fun normalize(input: String): String =
        input.lowercase()
            .split(" ")
            .filter { it.isNotBlank() }
            .joinToString(" ") { it.replaceFirstChar { c -> c.uppercase() } }
}